
#include "encyclopedia.h"
#include "Arduino.h"

#include <sprites.h>

//----------------------------------------------------------------------------------------------------------------

extern const char* file_list[]={
    "AERIAL",
    "AEROCH",
    "AEROTT",
    "AIRBEA",
    "ANGELB",
    "APARAS",
    "AQUAMO",
    "ARMORC",
    "BADGER",
    "BEASTM",
    "BEAVER",
    "BLOODH",
    "CARABO",
    "CATFIS",
    "CATMON",
    "CHAOSS",
    "CHEETA",
    "COASTM",
    "DARKLE",
    "DERUMO",
    "DIABOL",
    "DOGFIS",
    "DRACMO",
    "DRAGAR",
    "EXFLER",
    "EXKITT",
    "FIREBI",
    "FLAMEN",
    "FLERED",
    "GARUMO",
    "GOLDEN",
    "GOLDGR",
    "GORAMO",
    "HELLBI",
    "HELLCA",
    "HELLDO",
    "HORSEM",
    "HORUSM",
    "ICECRY",
    "IRONWO",
    "IVYMON",
    "JAGUAR",
    "KITTYD",
    "LAVAMO",
    "LEOPAR",
    "LILLYD",
    "MCHEET",
    "MEGAKI",
    "MEGALA",
    "METALD",
    "MFLERE",
    "MIROMO",
    "MIVYMO",
    "MPARAS",
    "MPORCU",
    "MTHYLA",
    "MVEEDR",
    "MYTHIC",
    "NADIMO",
    "OARUMO",
    "OTTARU",
    "OTTERM",
    "PARASA",
    "POLARM",
    "PORCUP",
    "RACOON",
    "RAPTOR",
    "RIKIMO",
    "ROOSTE",
    "SEALMO",
    "SERPEN",
    "SHIROM",
    "SHIZIM",
    "SKULLC",
    "SKUNKM",
    "SQUIRR",
    "THYLAC",
    "TIGERL",
    "VULTUR",
    "WARFLE",
    "WARIVY",
    "WARRIO",
    "ZEBRAM",
    "ZEMOGU"
};

extern const char* name_list[]={
    "Aerialmon",
    "Aerocheetahmon",
    "Aerottermon",
    "Airbeavermon",
    "Angelbirdmon",
    "A-parasaurmon",
    "Aquamon",
    "Armorcheetahmon",
    "Badgermon",
    "Beastmon",
    "Beavermon",
    "Bloodhoundmon",
    "Caraboamon",
    "Catfishmon",
    "Catmon",
    "ChaosSkullgreymon",
    "Cheetahmon",
    "Coastmon",
    "Darkleomon",
    "Derumon",
    "Diabolasmon",
    "Dogfishmon",
    "Dracmon",
    "Dragaramon",
    "Exfleredramon",
    "Exkittydramon",
    "Firebirdmon",
    "Flamengomon",
    "Fleredramon",
    "Garumon",
    "GoldenPheonixmon",
    "GoldGryphon",
    "Goramon",
    "Hellbirdmon",
    "Hellcatmon",
    "Helldogmon",
    "Horsemon",
    "Horusmon",
    "Icecrystalmon",
    "Ironwolfmon",
    "Ivymon",
    "Jaguarmon",
    "Kittydramon",
    "lavamon",
    "Leopardmon",
    "Lillydramon",
    "M-Cheetahmon",
    "Megakittydramon",
    "MegaLavamon",
    "Metaldramon",
    "M-Fleredramon",
    "Miromon",
    "M-Ivymon",
    "M-Parasaurmon",
    "M-Porcupinemon",
    "M-Thylacinemon",
    "MetalVeedramon",
    "Mythicmon",
    "Nadimon",
    "Oarumon",
    "Ottarumon",
    "Ottermon",
    "Parasaurmon",
    "Polarmon",
    "Porcupinemon",
    "Racoonmon",
    "Raptermon",
    "Rikimon",
    "Roostermon",
    "Sealmon",
    "Serpentmon",
    "Shiromon",
    "Shizimon",
    "Skullcheetahmon",
    "Skunkmon",
    "Squirrelmon",
    "Thylacinemon",
    "Tigerlillymon",
    "Vuturemon",
    "Warfleredramon",
    "WarIvymon",
    "Warriormon",
    "Zebramon",
    "Zemogumon"
};

extern const unsigned char* type_bitmaps[]={
    vaccine,
    data_d,
    virus,
};
//0=data, 1=vaccine, 2=virus
extern const int type_list[]={
    2,
    0,
    0,
    0,
    1,
    0,
    2,
    0,
    0,
    1,
    0,
    2,
    0,
    0,
    1,
    2,
    0,
    0,
    2,
    1,
    2,
    0,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    0,
    1,
    0,
    0,
    2,
    2,
    2,
    2,
    0,
    0,
    2,
    1,
    0,
    1,
    2,
    0,
    1,
    0,
    1,
    2,
    2,
    0,
    0,
    1,
    0,
    0,
    0,
    2,
    1,
    1,
    2,
    0,
    0,
    0,
    1,
    0,
    1,
    0,
    0,
    2,
    0,
    2,
    2,
    1,
    2,
    2,
    0,
    0,
    0,
    2,
    0,
    1,
    1,
    1,
    0
};

extern const unsigned char* element_bitmaps[]={
    fire,
    fighting,
    lightning,
    earth,
    sweat,
    mech,
    null_item
};

extern const int element_list[][3]={
    {2,0,1}, //"Aerialmon",
    {2,0,6}, //"Aerocheetahmon",
    {4,2,6}, //"Aerottermon",
    {4,2,1}, //"Airbeavermon",
    {2,0,6}, //"Angelbirdmon",
    {3,0,1}, //"A-parasaurmon",
    {4,3,0}, //"Aquamon",
    {4,0,2}, //"Armorcheetahmon",
    {4,1,6}, //"Badgermon",
    {1,2,0}, //"Beastmon,
    {4,1,6}, //"Beavermon",
    {0,1,6}, //"Bloodhoundmon",
    {0,6,6}, //"Caraboamon",
    {4,3,6}, //"Catfishmon",
    {2,1,6}, //"Catmon",
    {3,4,0}, //"ChaosSkullgreymon",
    {4,1,0}, //"Cheetahmon",
    {4,1,6}, //"Coastmon",
    {4,0,6}, //"Darkleomon",
    {0,2,6}, //"Derumon",
    {0,1,6}, //"Diabolasmon",
    {4,0,6}, //"Dogfishmon",
    {0,1,6}, //"Dracmon",
    {3,2,0}, //"Dragaramon",
    {0,1,6}, //"Exfleredramon",
    {1,2,6}, //"Exkittydramon",
    {0,2,6}, //"Firebirdmon",
    {2,0,6}, //"Flamengomon",
    {0,1,6}, //"Fleredramon",
    {1,2,0}, //"Garumon",
    {2,0,6}, //"GoldenPheonixmon",
    {0,2,6}, //"GoldGryphon",
    {0,3,6}, //"Goramon",
    {0,2,6}, //"Hellbirdmon",
    {0,1,6}, //"Hellcatmon",
    {0,1,6}, //"Helldogmon",
    {0,2,6}, //"Horsemon",
    {2,1,0}, //"Horusmon",
    {4,2,6}, //"Icecrystalmon",
    {0,4,6}, //"Ironwolfmon",
    {3,5,6}, //"Ivymon",
    {4,1,0}, //"Jaguarmon",
    {1,2,6}, //"Kittydramon",
    {0,1,6}, //"lavamon",
    {4,1,0}, //"Leopardmon",
    {3,1,6}, //"Lillydramon",
    {5,4,6}, //"M-Cheetahmon",
    {2,1,6}, //"Megakittydramon",
    {0,1,6}, //"MegaLavamon",
    {5,3,0}, //"Metaldramon",
    {0,5,1}, //"M-Fleredramon",
    {0,1,6}, //"Miromon",
    {3,5,6}, //"M-Ivymon",
    {3,5,0}, //"M-Parasaurmon,
    {2,5,1}, //"M-Porcupinemon",
    {1,2,6}, //"M-Thylacinemon,
    {5,0,6}, //"MetalVeedramon",
    {2,1,6}, //"Mythicmon",
    {2,4,0}, //"Nadimon",
    {0,1,6}, //"Oarumon",
    {4,3,6}, //"Ottarumon",
    {4,1,6}, //"Ottermon",
    {3,0,1}, //"Parasaurmon",
    {4,1,6}, //"Polarmon",
    {2,1,6}, //"Porcupinemon",
    {1,2,6}, //"Racoonmon",
    {0,1,6}, //"Raptermon",
    {2,1,6}, //"Rikimon",
    {2,1,0}, //"Roostermon",
    {4,1,6}, //"Sealmon",
    {4,0,3}, //"Serpentmon",
    {3,4,1}, //"Shiromon",
    {2,0,6}, //"Shizimon",
    {4,0,5}, //"Skullcheetahmon",
    {5,6,6}, //"Skunkmon",
    {1,2,6}, //"Squirrelmon",
    {2,1,0}, //"Thylacinemon",
    {3,0,6}, //"Tigerlillymon",
    {0,2,6}, //"Vuturemon",
    {0,1,5}, //"Wwarfleredramon",
    {3,0,5}, //"WarIvymon",
    {1,0,6}, //"Warriormon",
    {1,2,6}, //"Zebramon",
    {4,2,3}, //"Zemogumon"
};

//0=baby, 1=in-training, 2=rookie, 3=champion, 4=ultimate, 5=mega
extern const int level_list[]={
    5,
    4,
    4,
    5,
    5,
    3,
    3,
    5,
    4,
    4,
    3,
    4,
    5,
    4,
    4,
    5,
    3,
    5,
    4,
    4,
    5,
    3,
    4,
    4,
    3,
    3,
    3,
    3,
    3,
    4,
    4,
    5,
    4,
    4,
    4,
    5,
    4,
    3,
    3,
    5,
    3,
    2,
    2,
    4,
    4,
    2,
    5,
    5,
    5,
    4,
    4,
    3,
    5,
    4,
    5,
    5,
    4,
    3,
    3,
    5,
    3,
    2,
    2,
    5,
    4,
    3,
    3,
    2,
    4,
    3,
    5,
    3,
    3,
    5,
    3,
    2,
    3,
    3,
    3,
    5,
    5,
    3,
    3,
    3
};

//----------------------------------------------------------------------------------------------------------------

info_node::info_node(){
    species_name;
    file_name;
    type;
    elements;
    level;
}

void info_node::initialise(int species){
    species_name=name_list[species];
    file_name=file_list[species];
    type=type_list[species];
    elements[0]={element_list[species][0]};
    elements[1]={element_list[species][1]};
    elements[2]={element_list[species][2]};
    level=level_list[species];
}

const char* info_node::get_name(){
    return species_name;
}

const char* info_node::get_file_name(){
    return file_name;
}

int info_node::get_type_int(){
    return type;
}

const unsigned char* info_node::get_type_bitmap(){
    return type_bitmaps[type];
}

int* info_node::get_element_array(){
    return elements;
}

const unsigned char* info_node::get_element_bitmap(int element_int){
    return element_bitmaps[element_int];
}

int info_node::get_level(){
    return level;
}
//----------------------------------------------------------------------------------------------------------------


